config/routes.rb
Rails.application.routes.draw do
  
  get "/" => 'uni#index'
  post "uni/create" => "uni#create"
  get "uni/new" => "uni#new"
  
  get 'uni/login' => 'uni#login_form'
  post 'uni/login'
  get 'uni/logout'
  
  get "/event/index" => "event#index"
  post"/event/create" => "event#create"
  get"/event/new" => "event#new"
  
  
  get "uni/:id/edit" => "uni#edit"
  post "uni/:id/update" => "uni#update"
  get "uni/:id/show" => "uni#show"
  get "uni/:id/destroy" => "uni#destroy"
  
  
  get "event/:id/edit" => "event#edit"
  post "event/:id/update" => "event#update"
  get "event/:id/show" => "event#show"
  get "event/:id/destroy" => "event#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circle.rb
class Circle < ApplicationRecord
    validates :email,{presence: true,uniqueness: true}
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_name: params[:event_name], message: params[:message])
    @event.event_id=session[:uni_id]
    if @event.save
      flash[:info] = 'イベントを登録完了しました。'
      redirect_to event_index_path
    else
      flash[:info] = 'イベントを登録できませんでした。'
      render ("/event/new")
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to ("/event/index")
  end
  
  def show
    @event = Event.find_by(id: params[:id])
    @uni=Circle.find_by(id: @event.event_id.to_i)
  end
  
  def edit
    @event=Event.find_by(id: params[:id])
  end
  
  def update
    @event = Event.find_by(id: params[:id])
    @event.event_name = params[:event_name]
    @event.message = params[:message]
    if @event.save
      flash[:info] = 'イベントを更新しました。'
      redirect_to("/event/#{@event.id}/show")
    else
      flash[:info] = 'イベントを更新できませんでした。'
      redirect_to("/event/#{@event.id}/show")
    end
  end
  
end





#model event
      #event_name
      #event_id
      #message

app/controllers/uni_controller.rb
class UniController < ApplicationController
  
  def index
    @circles = Circle.all
  end
  
  def new
    @circle = Circle.new
  end
  
  def create
    
    @circle = Circle.new(uni_name: params[:uni_name],email: params[:email],pass: params[:pass],circle_name: params[:circle_name],top_name: params[:top_name])
    if @circle.save
      flash[:info] = 'ユーザを登録完了しました。'
      session[:uni_id] = @circle.id
      redirect_to("/")
    else
      render ("/uni/new")
    end
  end

  def edit
    @uni=Circle.find_by(id: params[:id])
  end

  def update
    @uni = Circle.find_by(id: params[:id])
    @uni.uni_name = params[:uni_name]
    @uni.email = params[:email]
    @uni.pass = params[:pass]
    @uni.circle_name = params[:circle_name]
    @uni.top_name = params[:top_name]
    if @uni.save
      flash[:info] = 'ユーザを更新しました。'
      redirect_to("/")
    else
      flash[:info] = 'ユーザを更新できませんでした。'
      redirect_to("/")
    end
  end
  
  
  def destroy
    @uni = Circle.find(params[:id])
    @events=Event.find_by(event_id: session[:uni_id].to_i)
    @uni.destroy
    if @events
      @events.destroy
    end
    session[:uni_id] = nil
    flash[:info]="退会しました"
    redirect_to ("/")
  end
  



  def login
    @uni = Circle.find_by(email: params[:email], pass: params[:pass])
    if @uni
      flash[:info] ="ログインしました"
      session[:uni_id] = @uni.id
      redirect_to "/"
    else
      flash[:info] = "メールアドレスまたはパスワードが間違っています"
      render ("uni/login_form") 
    end
  end
  
  def logout
    session[:uni_id] = nil
    flash[:info]="ログアウトしました"
    redirect_to "/"
  end
  
  def show
    @uni = Circle.find_by(id: params[:id])
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uni_helper.rb
module UniHelper
end

app/views/event/edit.html.erb
<div class="container">
  イベント編集

<%= form_tag("/event/#{@event.id}/update") do %>

  <p>イベント名</p>
  <input name="event_name"　value=<%= @event.event_name %> >
  <p>紹介文</p>
  <textarea name="message" value=<%= @event.message %> ></textarea><br>
  <input type="submit" value="編集">
<% end %>

<input type="button" value="戻る" onClick="history.back()">
</div>

app/views/event/index.html.erb
<div class="container">

<h2>イベント一覧</h2>


<% @events.each do |e| %>
    <p><%= link_to e.event_name ,"/event/#{e.id}/show" %>
<% end %>

</div>

app/views/event/new.html.erb
<div class="container">
  <%= form_tag("/event/create") do %>

<h1>イベント登録</h1>

<p>イベント名</p>
  <input name="event_name">
<p>紹介文</p>
  <textarea name="message"></textarea><br>
    <input type="submit" value="新規登録">
<% end %>

<input type="button" value="戻る" onClick="history.back()">

</div>

app/views/event/show.html.erb
<div class="container">

<div class="event_show">
    <h1><%= @event.event_name%></h1>
    主催校：<%= @uni.uni_name %></h1>
    <p>紹介文：<%= @event.message %></p>
    <p>最終更新日：<%= @event.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    <% if @event.event_id.to_i == session[:uni_id].to_i %>
        <%= link_to '編集', "/event/#{@event.id}/edit" %>
        <%= link_to '削除', "/event/#{@event.id}/destroy" %>
    <% end %>
</div>

    
<input type="button" value="戻る" onClick="history.back()">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FDC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<div class="flash">
  <% if flash[:info] %>
    <%= flash[:info] %>
    <% end %>
</div>
<div class="top_bar">
  <div class="login_now">
    <% if session[:uni_id] %>
      <p><%= Circle.find_by(id: session[:uni_id]).uni_name %>でログイン中<%= link_to '[編集]', "/uni/#{session[:uni_id]}/edit" %></p>
    <% end %>
  </div>

  <div class="header_menu">
    <ul>
      <li>
        <p><%= link_to '大学一覧', "/" %></p>
      </li>
      <li>
        <p><%= link_to 'イベント一覧', event_index_path %></p>
      </li>
      <li>
        <% if session[:uni_id] %>
          <p><%= link_to 'イベント作成', event_new_path %></p>
        <% else %>
          <p><%= link_to '大学登録', uni_new_path %></p>
        <% end %>
      </li>
      <li>
        <% if session[:uni_id] %>
          <p><%= link_to 'ログアウト', uni_logout_path %></p>
        <% else %>
          <p><%= link_to 'ログイン', uni_login_path %></p>
        <% end %>
      </li>
    </ul>
  </div>
</div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/uni/edit.html.erb
<div class="container">
大学編集

<%= form_tag("/uni/#{@uni.id}/update") do %>


<p>大学名（〇〇大学まで入力ください）</p>
  <input name="uni_name" value=<%= @uni.uni_name %> >
<p>メールアドレス</p>
  <input name="email" value=<%= @uni.email %>>
<p>パスワード</p>
  <input name="pass" value=<%= @uni.pass %>>
<p>サークル名</p>
  <input name="circle_name" value=<%= @uni.circle_name %>>
<p>代表者名</p>
  <input name="top_name" value=<%= @uni.top_name %>>
<br><br>
    <input type="submit" value="編集">
    <p>※登録済みメールアドレスは使えません</p>
<% end %>

<p><%= link_to '退会', "/uni/#{@uni.id}/destroy" %></p>
※大学、登録イベントが全て削除されます

<br>
<br>
<input type="button" value="戻る" onClick="history.back()">

</div>

app/views/uni/index.html.erb
<div class="container">
    <h2>大学一覧</h2>
    <% @circles.each do |c| %>
        <p><%= link_to c.uni_name ,"/uni/#{c.id}/show" %></p>
    <% end %>
</div>

app/views/uni/login_form.html.erb
<div class="container">
  <%= form_tag("/uni/login") do %>
  <p>メールアドレス</p>
  <input name="email" value="<%= @email %>">
  
  <p>パスワード</p>
  <input type="password" name="pass" value="<%= @pass %>">
  
  <%= submit_tag "ログイン" %>
<% end %>

<input type="button" value="戻る" onClick="history.back()">
</div>

app/views/uni/new.html.erb
<div class="container">
新規大学登録






<%= form_tag("/uni/create") do %>


<p>大学名（〇〇大学まで入力ください）</p>
  <input name="uni_name">
<p>メールアドレス</p>
  <input name="email">
<p>パスワード</p>
  <input name="pass">
<p>サークル名</p>
  <input name="circle_name">
<p>代表者名</p>
  <input name="top_name">
<br><br>
    <input type="submit" value="新規登録">
    <p>※登録済みメールアドレスは使えません</p>
<% end %>

</div>

app/views/uni/show.html.erb
<div class="container">
    
    <h1><%= @uni.uni_name%> </h1>
    
    <p>大学名：<%= @uni.uni_name%></p>
    <p>サークル名：<%= @uni.circle_name%></p>
    <p>代表者：<%= @uni.top_name%></p>
    
    
    
    
    
    
    <p>最終更新日</p>
    <p><%= @uni.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    
    <h1>開催イベント</h1>
        <div class="uni_event">
            <% @events.each do |e| %>
            <% if e.event_id.to_i == @uni.id.to_i %>
                <p><%= link_to e.event_name ,"/event/#{e.id}/show" %></p>
            <% end %>
        <% end %>
    
        </div>

<input type="button" value="戻る" onClick="history.back()">
    
    
</div>